server:
  port: 8081

spring:
  application:
    name: actuator-demo-app

management:
  endpoints:
    web:
      exposure:
        include: health,info,env
  endpoint:
    health:
      show-details: always
